"""Add name field to User model

Revision ID: 1b1a28f52e78
Revises: 40c1a1ba7f8a
Create Date: 2025-03-08 11:59:22.952233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1a28f52e78'
down_revision = '40c1a1ba7f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.drop_column('is_admin')
        batch_op.drop_column('bio')
        batch_op.drop_column('last_login')
        batch_op.drop_column('created_at')
        batch_op.drop_column('profile_image')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('profile_image', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('name')

    op.create_table('job',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), nullable=False),
    sa.Column('job_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('salary_min', sa.FLOAT(), nullable=True),
    sa.Column('salary_max', sa.FLOAT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('requirements', sa.TEXT(), nullable=False),
    sa.Column('benefits', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
